<!-- app/code/DigitalHub/DoubleCheck/view/adminhtml/templates/system/config/advanced_button.phtml -->
<div class="admin__actions">
    <button id="<?php echo $block->escapeHtml($block->getId()) ?>" class="admin__action-button" type="button" title="<?php echo $block->escapeHtml($block->getTitle()) ?>" onclick="window.location.href='<?php echo $block->getUrl($block->getActionPath()) ?>';">
        <span><?php echo $block->escapeHtml($block->getLabel()) ?></span>
    </button>
</div>
